//package org.mariadb.jdbc.hotfix;
//
//import org.mariadb.jdbc.*;
//import org.mariadb.jdbc.internal.util.exceptions.*;
//
//import java.sql.*;
//
//public class ClientSidePreparedStatement2 extends ClientSidePreparedStatement {
//    /**
//     * Constructor.
//     *
//     * @param connection           connection
//     * @param sql                  sql query
//     * @param resultSetScrollType  one of the following <code>ResultSet</code> constants: <code>
//     *                             ResultSet.TYPE_FORWARD_ONLY</code>, <code>ResultSet.TYPE_SCROLL_INSENSITIVE</code>, or
//     *                             <code>ResultSet.TYPE_SCROLL_SENSITIVE</code>
//     * @param resultSetConcurrency a concurrency type; one of <code>ResultSet.CONCUR_READ_ONLY</code>
//     *                             or <code>ResultSet.CONCUR_UPDATABLE</code>
//     * @param autoGeneratedKeys    a flag indicating whether auto-generated keys should be returned; one
//     *                             of <code>Statement.RETURN_GENERATED_KEYS</code> or <code>Statement.NO_GENERATED_KEYS</code>
//     * @param exceptionFactory     exception factory
//     * @throws SQLException exception
//     */
//    public ClientSidePreparedStatement2(MariaDbConnection connection, String sql, int resultSetScrollType, int resultSetConcurrency, int autoGeneratedKeys, ExceptionFactory exceptionFactory) throws SQLException {
//        super(connection, sql, resultSetScrollType, resultSetConcurrency, autoGeneratedKeys, exceptionFactory);
//    }
//
//
//
//}