//package org.mariadb.jdbc.hotfix;
//
//import org.mariadb.jdbc.*;
//import org.mariadb.jdbc.internal.protocol.*;
//
//import java.sql.*;
//
//public class MariaDbConnection2 extends MariaDbConnection {
//    /**
//     * Creates a new connection with a given protocol and query factory.
//     *
//     * @param protocol the protocol to use.
//     */
//    public MariaDbConnection2(Protocol protocol) {
//        super(protocol);
//    }
//
//    @Override
//    public Statement createStatement() throws SQLException {
//        MariaDbStatement ret = (MariaDbStatement) super.createStatement();
//        return ret;
//    }
//
//    @Override
//    public Statement createStatement(int resultSetType, int resultSetConcurrency) {
//        MariaDbStatement ret = (MariaDbStatement) super.createStatement(resultSetType, resultSetConcurrency);
//        return ret;
//    }
//
//    @Override
//    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) {
//        MariaDbStatement ret = (MariaDbStatement) super.createStatement(resultSetType, resultSetConcurrency, resultSetHoldability);
//
//        return ret;
//    }
//
//    @Override
//    protected PreparedStatement internalPrepareStatement(String sql, int resultSetScrollType, int resultSetConcurrency, int autoGeneratedKeys) throws SQLException {
//        ClientSidePreparedStatement ret = (ClientSidePreparedStatement) super.internalPrepareStatement(sql, resultSetScrollType, resultSetConcurrency, autoGeneratedKeys);
//
//        return ret;
//    }
//
//
//
//}