//package org.mariadb.jdbc.hotfix;
//
//import org.mariadb.jdbc.*;
//import org.mariadb.jdbc.internal.util.exceptions.*;
//
//import java.sql.*;
//
//public class MariaDbStatement2 extends MariaDbStatement {
//
//    protected ResultSet lastResultSet;
//    /**
//     * Creates a new Statement.
//     *
//     * @param connection           the connection to return in getConnection.
//     * @param resultSetScrollType  one of the following <code>ResultSet</code> constants: <code>
//     *                             ResultSet.TYPE_FORWARD_ONLY</code>, <code>ResultSet.TYPE_SCROLL_INSENSITIVE</code>, or
//     *                             <code>ResultSet.TYPE_SCROLL_SENSITIVE</code>
//     * @param resultSetConcurrency a concurrency type; one of <code>ResultSet.CONCUR_READ_ONLY</code>
//     *                             or <code>ResultSet.CONCUR_UPDATABLE</code>
//     * @param exceptionFactory     exception factory
//     */
//    public MariaDbStatement2(MariaDbConnection connection, int resultSetScrollType, int resultSetConcurrency, ExceptionFactory exceptionFactory) {
//        super(connection, resultSetScrollType, resultSetConcurrency, exceptionFactory);
//    }
//
//    @Override
//    public boolean execute(String sql) throws SQLException {
//        return super.execute(sql);
//    }
//
//    @Override
//    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
//        return super.execute(sql, autoGeneratedKeys);
//    }
//
//    @Override
//    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
//        return super.execute(sql, columnIndexes);
//    }
//
//    @Override
//    public boolean execute(String sql, String[] columnNames) throws SQLException {
//        return super.execute(sql, columnNames);
//    }
//
//    @Override
//    public ResultSet executeQuery(String sql) throws SQLException {
//        return super.executeQuery(sql);
//    }
//
//    @Override
//    public ResultSet getResultSet() throws SQLException {
//        return super.getResultSet();
//    }
//}